version: "3"

services:
  web:
    image: webdevops/php-apache:7.4
    restart: always
    container_name: server_web
    ports:
      - "4500:80"
    volumes:
      - ../my-folder-name-here:/app

  db:
    image: mariadb:10.3
    container_name: server_mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      # MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_name_here
      MYSQL_PASSWORD: root

  phpmyadmin:
    container_name: server_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      # MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
